### ISSUE TITLE
circular dependency

### ISSUE THREAD

**Issue by cup** [bloom42/rz-go#10]
it seems the package requires... itself:

~~~
$ go get -v github.com/bloom42/rz-go/v2
github.com/bloom42/rz-go (download)
package github.com/bloom42/rz-go/v2: cannot find package
"github.com/bloom42/rz-go/v2" in any of:
   c:\go\src\github.com\bloom42\rz-go\v2 (from $GOROOT)
   C:\Users\Steven\go\src\github.com\bloom42\rz-go\v2 (from $GOPATH)
~~~

**Comment by z0mbie42** [comment]
Hi,
Which version of go do you use.

I think your error come from the (sad) state of go package management:

to use `rz` you need to use go modules and so your `go get` must be made in a directory with a `go.mod` file.

**Comment by cup** [comment]
~~~
$ go version
go version go1.12.5 windows/amd64
~~~

**Comment by z0mbie42** [comment]
Did you `go get` in a directory with a `go.mod` file ? Because it works fine on my side

**Comment by cup** [comment]
@z0mbie42 sorry but i have no idea what you are talking about.

Normally I `go get` in any random directory regardless of what files are in it.

1. why does it matter what directory i am in
2. why does `go.mod` need to exist

**Comment by z0mbie42** [comment]
Go modules is the way forward to manage go projects dependencies: https://blog.golang.org/using-go-modules

`rz` is only available with go modules because of the `v2` things which is kind of a 'soft path' (not present in the url nor in the folders tree

**Comment by cup** [comment]
@z0mbie42 can you please get an example command to fix the problem, so that I dont have to comb through a 2,000 word document?

**Comment by z0mbie42** [comment]
```sh
$ go version
go version go1.12.5 linux/amd64
$ wget https://raw.githubusercontent.com/bloom42/rz-go/master/examples/simple/main.go
[...]
$ echo "module github.com/test/test" > go.mod
$ go run main.go
go: finding github.com/bloom42/rz-go/v2 v2.6.0
go: finding github.com/bloom42/rz-go/v2/log latest
go: downloading github.com/bloom42/rz-go/v2 v2.6.0
go: extracting github.com/bloom42/rz-go/v2 v2.6.0
[...]
```

**Comment by z0mbie42** [comment]
you can also `go mod init` at the root of your package

**Comment by cup** [comment]
@z0mbie42 it might be a good idea to add what you just put here:

https://github.com/bloom42/rz-go

as is done with most Go packages:

- https://github.com/francoispqt/onelog#get-started
- https://github.com/go-playground/log#installation
- https://github.com/rs/zerolog#installation
- https://github.com/uber-go/zap#installation

for anyone else visiting this page, this shorter commands seems to work:

~~~
go mod init github.com/bloom42/rz-go
go get
~~~

**Comment by z0mbie42** [comment]
Good idea, I'll add it at the end of the day.
