### ISSUE TITLE
Configurable log levels

### ISSUE THREAD

**Issue by wayneashleyberry** [bloom42/rz-go#4]
It would be great if we could configure `rz` log levels beyond field names.

Stackdriver, for example, supports 9 levels of severity: https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#logseverity

**Comment by z0mbie42** [comment]
Hello,

Do you have an idea of how to proceed ?

On the other side I'm not convinced that more than 5/6 levels is a good design and would introduce too much headache for implementers.

**Comment by z0mbie42** [comment]
Hi again,

Do you see actionable steps to solve this issue ?

**Comment by wayneashleyberry** [comment]
I'll close this until I have a better idea of the exact requirements I have @z0mbie42, I do think that adaptors for major cloud providers are important though.
